"""add email column to users

Revision ID: ce654c3b8328
Revises: ecd898b658f6
Create Date: 2025-09-07 03:18:53.203990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce654c3b8328'
down_revision = 'ecd898b658f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email_unique', sqlite_where=sa.text('email IS NOT NULL'))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_email_unique', ['email'], unique=1, sqlite_where=sa.text('email IS NOT NULL'))

    # ### end Alembic commands ###
